LESSONS.push(
L({id:"cl1", day:"06", ch:"Closures", level:"Intermediate", title:"Basic closures", hint:"A function with no name.",
    lines:["[let] [sayHi] = [{] [print](\"hi\") [}]","[sayHi]()"],
    notes:{0:"Inferred () -> Void.",1:"Call the stored closure."}}),
  L({id:"cl2", day:"06", ch:"Closures", level:"Intermediate", title:"Closures as parameters", hint:"Hand a block over.",
    lines:["[func] [run]([work]: [() -> Void]) {","[work]()","}"],
    notes:{0:"work’s type is a function.",1:"Runs whatever was passed."}}),
  L({id:"cl3", day:"06", ch:"Closures", level:"Intermediate", title:"Trailing + $0", hint:"Shorthand argument.",
    lines:["[let] [doubled] = [nums].[map] [{] [$0] * [2] [}]"],
    notes:{0:"Trailing closure. $0 is the current element."}}),
  L({id:"st1", day:"07", ch:"Structs", level:"Intermediate", title:"Creating structs", hint:"Value type.",
    lines:["[struct] [Sport] {","[var] [name]: [String]","}","[let] [tennis] = [Sport](name: \"Tennis\")"],
    notes:{0:"Value type. Copied on assign.",1:"Stored property.",3:"Memberwise init is free."}}),
  L({id:"st2", day:"07", ch:"Structs", level:"Intermediate", title:"Computed properties", hint:"A property that runs code.",
    lines:["[struct] [Sport] {","[var] [name]: [String]","[var] [isOlympic]: [Bool] { [true] }","}"],
    notes:{2:"isOlympic is computed. No stored slot."}}),
  L({id:"st3", day:"07", ch:"Structs", level:"Intermediate", title:"Property observers", hint:"didSet runs after a change.",
    lines:["[struct] [Prog] {","[var] [amount] = [0] {","[didSet] { [print]([amount]) }","}","}"],
    notes:{2:"didSet fires after amount changes."}}),
  L({id:"st4", day:"07", ch:"Structs", level:"Intermediate", title:"Mutating methods", hint:"struct methods that change self.",
    lines:["[struct] [Bank] {","[var] [cash] = [0]","[mutating] [func] [deposit]([_] [n]: [Int]) {","[cash] [+=] [n]","}","}"],
    notes:{2:"Without mutating, cash += n is an error."}}),
  L({id:"st5", day:"07", ch:"Structs", level:"Intermediate", title:"self in init", hint:"Tell properties apart from params.",
    lines:["[struct] [User] {","[var] [name]: [String]","[init]([name]: [String]) {","[self].[name] = [name]","}","}"],
    notes:{3:"self.name is the property. name on the right is the parameter."}}),
  L({id:"st6", day:"08", ch:"Structs", level:"Intermediate", title:"Static members", hint:"Belongs to the type.",
    lines:["[struct] [App] {","[static] [let] [version] = [\"1.0\"]","}","[print]([App].[version])"],
    notes:{1:"No instance needed.",3:"App.version — type name."}}),
  L({id:"clss1", day:"09", ch:"Classes", level:"Intermediate", title:"Creating classes", hint:"Reference type.",
    lines:["[class] [Dog] {","[var] [name]: [String]","[init]([name]: [String]) { [self].[name] = [name] }","}"],
    notes:{0:"Reference type. Shared on assign.",2:"Classes do not get a free memberwise init."}}),
  L({id:"clss2", day:"09", ch:"Classes", level:"Intermediate", title:"Inheritance", hint:"Subclass adds or replaces.",
    lines:["[class] [Poodle]: [Dog] {","[func] [trim]() { [print](\"trim\") }","}"],
    notes:{0:"Poodle is a Dog."}}),
  L({id:"clss3", day:"09", ch:"Classes", level:"Intermediate", title:"override", hint:"Replace the parent method.",
    lines:["[class] [Poodle]: [Dog] {","[override] [func] [makeNoise]() {","[print](\"yip\")","}","}"],
    notes:{1:"Signature must match the superclass method."}}),
  L({id:"clss4", day:"09", ch:"Classes", level:"Intermediate", title:"final classes", hint:"No further subclassing.",
    lines:["[final] [class] [ClosedDog] {","[var] [name] = [\"Rex\"]","}"],
    notes:{0:"class Other: ClosedDog is a compiler error."}}),
  L({id:"clss5", day:"10", ch:"Classes", level:"Intermediate", title:"Copying vs sharing", hint:"class is shared.",
    lines:["[var] [a] = [Dog](name: \"Fido\")","[var] [b] = [a]","[b].[name] = [\"Rex\"]"],
    notes:{1:"b and a point at the same object."}}),
  L({id:"p1", day:"11", ch:"Protocols", level:"Advanced", title:"A protocol is a contract", hint:"Required methods only.",
    lines:["[protocol] [Fizzable] {","[func] [isFizz]() [->] [Bool]","}"],
    notes:{0:"Not a type you init.",1:"Conforming types must implement this."}}),
  L({id:"p2", day:"11", ch:"Protocols", level:"Advanced", title:"Protocol inheritance", hint:"One contract requires two others.",
    lines:["[protocol] [FizzBuzzable]: [Fizzable], [Buzzable] [{][}]"],
    notes:{0:"Conformance still needs isFizz and isBuzz."}}),
  L({id:"p3", day:"11", ch:"Protocols", level:"Advanced", title:"Int conforms", hint:"Give Int the two methods.",
    lines:["[extension] [Int]: [FizzBuzzable] {","[func] [isFizz]() [->] [Bool] { [self] % [3] == [0] }","[func] [isBuzz]() [->] [Bool] { [self] % [5] == [0] }","}"],
    notes:{0:"Compiler now demands both methods."}}),
  L({id:"p4", day:"11", ch:"Protocols", level:"Advanced", title:"Default label()", hint:"Write the words once.",
    lines:["[extension] [FizzBuzzable] {","[func] [label]() [->] [String] {","[if] [isFizz]() && [isBuzz]() { [return] [\"FizzBuzz\"] }","[if] [isFizz]() { [return] [\"Fizz\"] }","[if] [isBuzz]() { [return] [\"Buzz\"] }","[return] [\"\\(self)\"]","}","}"],
    notes:{0:"Default implementation. Int inherits it."}}),
  L({id:"p5", day:"11", ch:"Protocols", level:"Advanced", title:"Protocol extensions", hint:"Share code across adopters.",
    lines:["[extension] [Identifiable] {","[func] [describe]() [->] [String] {","[return] [\"id: \\(id)\"]","}","}"],
    notes:{0:"Any Identifiable gets describe() for free."}}),
  L({id:"op1", day:"12", ch:"Optionals", level:"Advanced", title:"Unwrapping with if let", hint:"Only enter if it exists.",
    lines:["[if] [let] [name] = [username] {","[print]([name])","}"],
    notes:{0:"If username is nil, the block is skipped."}}),
  L({id:"op2", day:"12", ch:"Optionals", level:"Advanced", title:"guard let", hint:"Bail out early.",
    lines:["[guard] [let] [name] = [username] [else] { [return] }","[print]([name])"],
    notes:{0:"else MUST exit."}}),
  L({id:"op3", day:"12", ch:"Optionals", level:"Advanced", title:"Nil coalescing", hint:"Default when nil.",
    lines:["[let] [name] = [username] [??] [\"Anonymous\"]"],
    notes:{0:"If username is nil, use Anonymous."}}),
  L({id:"op4", day:"12", ch:"Optionals", level:"Advanced", title:"Optional chaining", hint:"Stop if nil.",
    lines:["[let] [count] = [album]?.[name].[count]"],
    notes:{0:"If album is nil, whole expression is nil."}}),
  L({id:"op5", day:"12", ch:"Optionals", level:"Advanced", title:"Typecasting", hint:"as? might fail.",
    lines:["[if] [let] [dog] = [pet] [as?] [Dog] {","[print]([dog].[name])","}"],
    notes:{0:"as? returns Dog?."}}),
  L({id:"pr1", day:"13", ch:"Projects", level:"Projects", title:"Project 1 · Storm list", hint:"Array of picture names like Storm Viewer.",
    lines:["[var] [pictures] = [[String]]()","[pictures].[append](\"nssl0049.jpg\")","[print]([pictures].[count])"],
    notes:{0:"Empty [String] — the table data source."}}),
  L({id:"pr2", day:"13", ch:"Projects", level:"Projects", title:"Project 1 · Pick a row", hint:"Tap a storm, read its name.",
    lines:["[let] [name] = [pictures][[indexPath].[row]]","[print]([name])"],
    notes:{0:"indexPath.row is the Int index."}}),
  L({id:"pr3", day:"14", ch:"Projects", level:"Projects", title:"Project 2 · Flag countries", hint:"Guess the Flag data.",
    lines:["[var] [countries] = [\"Estonia\", \"France\", \"Germany\"]","[countries].[shuffle]()","[let] [correct] = [Int].[random](in: 0...2)"],
    notes:{0:"Three flag names."}}),
  L({id:"pr4", day:"14", ch:"Projects", level:"Projects", title:"Project 2 · Score a tap", hint:"Right flag adds a point.",
    lines:["[if] [sender].[tag] [==] [correct] {","[score] [+=] [1]","}"],
    notes:{0:"Each button’s tag is 0, 1, or 2."}}),
  L({id:"pr5", day:"15", ch:"Projects", level:"Projects", title:"Project 4 · Easy Browser URL", hint:"Load a site.",
    lines:["[let] [url] = [URL](string: \"https://hackingwithswift.com\")","[let] [req] = [URLRequest](url: url!)","[webView].[load]([req])"],
    notes:{0:"URL(string:) returns URL?."}}),
  L({id:"pr6", day:"16", ch:"Projects", level:"Projects", title:"Project · FizzBuzz app", hint:"Full protocol FizzBuzz runner.",
    lines:["[func] [printFizzBuzz]([from] [start]: [Int], [through] [end]: [Int]) {","[for] [n] [in] [start] [...] [end] {","[print]([n].[label]())","}","}"],
    notes:{2:"Int is FizzBuzzable so label() exists."}}),
  L({id:"pr7", day:"17", ch:"Projects", level:"Projects", title:"Project · Word scramble score", hint:"Used in the anagram game.",
    lines:["[func] [score]([word]: [String]) [->] [Int] {","[return] [word].[count]","}"],
    notes:{0:"Returns Int — longer word, higher score."}}),
  L({id:"pr8", day:"18", ch:"Projects", level:"Projects", title:"Project · Notes model", hint:"A struct you persist.",
    lines:["[struct] [Note]: [Identifiable], [Codable] {","[let] [id] = [UUID]()","[var] [text]: [String]","}"],
    notes:{0:"Identifiable for lists. Codable for JSON save."}})
);
