const DONE_KEY="swift-tap-done-v3";
const done=new Set(JSON.parse(localStorage.getItem(DONE_KEY)||"[]"));
const save=()=>localStorage.setItem(DONE_KEY,JSON.stringify([...done]));
function exportProgress(){
  const text=JSON.stringify({v:3,done:[...done]});
  if(navigator.clipboard&&navigator.clipboard.writeText){ navigator.clipboard.writeText(text).catch(()=>{}); }
  alert("Progress copied. Paste it later with Restore.");
}
function importProgress(){
  const raw=prompt("Paste your saved progress JSON:");
  if(!raw) return;
  try{
    const data=JSON.parse(raw);
    const list=Array.isArray(data)?data:data.done;
    list.forEach(id=>done.add(id));
    save(); renderHome(); alert("Progress restored.");
  }catch(e){ alert("That was not valid progress data."); }
}
const COMPILER = {
  var:"Action: bind a name you can change.",
  let:"Action: bind a constant. Later assignment is an error.",
  func:"Action: declare a function.",
  return:"Action: send a value back. Must match -> Type.",
  print:"Action: Void standard-library call.",
  if:"Action: branch. Test must be Bool.",
  else:"Action: the other branch of an if.",
  switch:"Action: match one value against cases.",
  case:"Action: one possible match in switch or enum.",
  default:"Action: catch-all case.",
  for:"Action: start a loop over a sequence.",
  while:"Action: loop that re-checks a Bool.",
  repeat:"Action: run the body once, then test.",
  in:"Action: connect the loop variable to the sequence.",
  break:"Action: leave the nearest loop or switch now.",
  continue:"Action: skip the rest of this loop trip.",
  struct:"Action: declare a value type.",
  class:"Action: declare a reference type.",
  enum:"Action: declare a type with a fixed list of cases.",
  protocol:"Action: declare a contract.",
  extension:"Action: add methods or conformance.",
  mutating:"Action: mark a struct method that changes self.",
  override:"Action: replace a superclass method.",
  final:"Action: lock a class or method.",
  init:"Action: construct an instance.",
  self:"Action: name the current instance.",
  guard:"Action: early-exit check.",
  throws:"Action: this function can throw.",
  try:"Action: call a throwing function.",
  inout:"Action: pass-by-reference. Caller writes &.",
  static:"Action: belongs to the type.",
  Int:"Integer type.", String:"Text type.", Double:"Floating-point type.", Bool:"true or false.",
  Void:"No value.",
  "...":"Closed range.",
  "+=":"Compound assignment.",
  "==":"Equality test.",
  ">=":"Greater-or-equal.",
  "&&":"Logical and.",
  "->":"Return-type arrow.",
  "_":"Wildcard.",
  "$0":"Shorthand closure argument.",
  map:"Transform every element.",
  Fizzable:"Protocol for isFizz().",
  Buzzable:"Protocol for isBuzz().",
  FizzBuzzable:"Inherits Fizzable and Buzzable.",
  isFizz:"Required protocol method.",
  isBuzz:"Required protocol method.",
  label:"Turns rules into a String."
};
const L = (o)=>({level:o.level||"Beginner", ...o});
const LESSONS = [
  L({id:"s1", day:"01", ch:"Simple Types", title:"Variables", hint:"A name you can change.",
    lines:["[var] [score] = [10]","[score] = [20]","[print]([score])"],
    notes:{0:"Compiler infers Int from 10.",1:"Assignment allowed because of var.",2:"print is Void."}}),
  L({id:"s2", day:"01", ch:"Simple Types", title:"Strings and integers", hint:"Quotes vs no quotes.",
    lines:["[var] [name] = [\"Taylor\"]","[var] [age] = [26]"],
    notes:{0:"Quotes make String.",1:"No quotes make Int."}}),
  L({id:"s3", day:"01", ch:"Simple Types", title:"Multi-line strings", hint:"Newlines inside one string.",
    lines:["[let] [bio] = [\"Born\\nin CA\"]","[print]([bio])"],
    notes:{0:"\\n is a newline inside the String."}}),
  L({id:"s4", day:"01", ch:"Simple Types", title:"Doubles and booleans", hint:"Decimal and true/false.",
    lines:["[let] [pi] = [3.141]","[let] [ready] = [true]"],
    notes:{0:"Dot makes Double.",1:"Bool."}}),
  L({id:"s5", day:"01", ch:"Simple Types", title:"String interpolation", hint:"Drop a value inside text.",
    lines:["[let] [name] = [\"Ada\"]","[let] [msg] = [\"Hi \\(name)!\"]"],
    notes:{1:"\\(name) is interpolation."}}),
  L({id:"s6", day:"01", ch:"Simple Types", title:"Constants", hint:"let cannot change.",
    lines:["[let] [city] = [\"Rocklin\"]","[print]([city])"],
    notes:{0:"Reassigning city is an error."}}),
  L({id:"s7", day:"01", ch:"Simple Types", title:"Type annotations", hint:"You tell Swift the type.",
    lines:["[var] [score]: [Int] = [0]","[var] [player]: [String] = [\"You\"]"],
    notes:{0:": Int is checked against 0."}}),
  L({id:"c1", day:"02", ch:"Complex Types", title:"Arrays", hint:"Ordered list.",
    lines:["[let] [names] = [\"Ed\", \"Taylor\"]","[print]([names][0])"],
    notes:{0:"Inferred as [String]."}}),
  L({id:"c2", day:"02", ch:"Complex Types", title:"Sets", hint:"Unique, unordered.",
    lines:["[let] [colors] = [Set]([\"red\", \"red\"])","[print]([colors].[count])"],
    notes:{0:"Set drops the duplicate red."}}),
  L({id:"c3", day:"02", ch:"Complex Types", title:"Tuples", hint:"Fixed mixed bundle.",
    lines:["[let] [person] = [(name: \"Ada\", age: 36)]","[print]([person].[name])"],
    notes:{0:"Tuple with labels."}}),
  L({id:"c4", day:"02", ch:"Complex Types", title:"Dictionaries", hint:"Key to value.",
    lines:["[let] [h] = [\"Taylor\": 1.78]","[print]([h][\"Taylor\"])"],
    notes:{1:"Lookup is Double?."}}),
  L({id:"c5", day:"02", ch:"Complex Types", title:"Dictionary defaults", hint:"Fallback if missing.",
    lines:["[let] [n] = [results][\"pass\", [default]: [0]]"],
    notes:{0:"Missing key becomes 0."}}),
  L({id:"c6", day:"02", ch:"Complex Types", title:"Empty collections", hint:"Type required when empty.",
    lines:["[var] [teams] = [[String]]()","[var] [scores] = [[String]: [Int]]()"],
    notes:{0:"Empty Array of String."}}),
  L({id:"c7", day:"02", ch:"Complex Types", title:"Enumerations", hint:"Fixed list of cases.",
    lines:["[enum] [Weather] {","[case] [sun]","[case] [rain]","}"],
    notes:{0:"New type Weather."}}),
  L({id:"c8", day:"02", ch:"Complex Types", title:"Enum associated values", hint:"A case can carry data.",
    lines:["[enum] [Activity] {","[case] [talking]([String])","[case] [running]([Int])","}"],
    notes:{1:"talking carries a String."}}),
  L({id:"c9", day:"02", ch:"Complex Types", title:"Enum raw values", hint:"Each case maps to a raw value.",
    lines:["[enum] [Planet]: [Int] {","[case] [mercury] = [1]","[case] [venus]","}"],
    notes:{2:"venus becomes 2."}}),
  L({id:"o1", day:"03", ch:"Operators", title:"Arithmetic", hint:"+ * %",
    lines:["[let] [a] = [12] + [8]","[let] [c] = [10] % [3]"],
    notes:{1:"Remainder. c is 1."}}),
  L({id:"o2", day:"03", ch:"Operators", title:"Compound assignment", hint:"Change in place.",
    lines:["[var] [score] = [50]","[score] [+=] [10]"],
    notes:{1:"score = score + 10."}}),
  L({id:"o3", day:"03", ch:"Operators", title:"Conditions", hint:"if needs a Bool.",
    lines:["[let] [score] = [85]","[if] [score] [>=] [80] {","[print](\"pass\")","}"],
    notes:{1:">= returns Bool."}}),
  L({id:"o4", day:"03", ch:"Operators", title:"Combining conditions", hint:"&& and ||",
    lines:["[if] [age] [>=] [18] [&&] [hasID] {","[print](\"in\")","}"],
    notes:{0:"Both Bools must be true."}}),
  L({id:"o5", day:"03", ch:"Operators", title:"Ternary operator", hint:"Pick A or B in one line.",
    lines:["[let] [wear] = [isRain] [?] [\"coat\"] [:] [\"shirt\"]"],
    notes:{0:"true -> coat, false -> shirt."}}),
  L({id:"o6", day:"03", ch:"Operators", title:"Switch and case", hint:"Exhaustive matching.",
    lines:["[switch] [weather] {","[case] [\"sun\"]: [print](\"hot\")","[default]: [print](\"other\")","}"],
    notes:{0:"default is required for String."}}),
  L({id:"o7", day:"03", ch:"Operators", title:"Range operators", hint:"Closed vs half-open.",
    lines:["[for] [i] [in] [1][...][5] {","[print]([i])","}"],
    notes:{0:"1...5 includes 5."}}),
  L({id:"l1", day:"04", ch:"Looping", title:"For loops", hint:"Walk every item.",
    lines:["[let] [names] = [\"A\", \"B\"]","[for] [name] [in] [names] {","[print]([name])","}"],
    notes:{1:"name is String each trip."}}),
  L({id:"l2", day:"04", ch:"Looping", title:"for _ in 1 ... times", hint:"Repeat without the number.",
    lines:["[for] [_] [in] [1] [...] [times] {","[result] [+=] [name]","}"],
    notes:{0:"_ discards the index."}}),
  L({id:"l3", day:"04", ch:"Looping", title:"While loops", hint:"Test first.",
    lines:["[var] [n] = [1]","[while] [n] [<=] [3] {","[n] [+=] [1]","}"],
    notes:{1:"Re-checks Bool every time."}}),
  L({id:"l4", day:"04", ch:"Looping", title:"Repeat loops", hint:"Body first.",
    lines:["[repeat] {","[print]([n])","} [while] [n] [<] [1]"],
    notes:{0:"Body runs before the test."}}),
  L({id:"l5", day:"04", ch:"Looping", title:"break", hint:"Leave now.",
    lines:["[for] [i] [in] [1][...][10] {","[if] [i] [==] [3] { [break] }","}"],
    notes:{1:"break exits."}}),
  L({id:"l6", day:"04", ch:"Looping", title:"continue", hint:"Skip this trip.",
    lines:["[for] [i] [in] [1][...][4] {","[if] [i] [==] [2] { [continue] }","[print]([i])","}"],
    notes:{1:"2 is skipped."}}),
  L({id:"f1", day:"05", ch:"Functions", title:"Writing functions", hint:"Named block.",
    lines:["[func] [greet]() {","[print](\"hello\")","}","[greet]()"],
    notes:{0:"Void function."}}),
  L({id:"f2", day:"05", ch:"Functions", title:"Accepting parameters", hint:"Inputs in ().",
    lines:["[func] [square]([number]: [Int]) {","[print]([number] * [number])","}"],
    notes:{0:"Must pass an Int labeled number."}}),
  L({id:"f3", day:"05", ch:"Functions", title:"Returning values", hint:"-> is the contract.",
    lines:["[func] [square]([number]: [Int]) [->] [Int] {","[return] [number] * [number]","}"],
    notes:{1:"return matches -> Int."}}),
  L({id:"f4", day:"05", ch:"Functions", title:"printResumes the bug", hint:"Void vs String.",
    lines:["[func] [printResumes]([times]: [Int], [name]: [String]) {","[var] [result] = [\"\"]","[return] [result]","}"],
    notes:{0:"Void function.",2:"ERROR. return String from Void."}}),
  L({id:"f5", day:"05", ch:"Functions", title:"printResumes fixed", hint:"print instead of return.",
    lines:["[func] [printResumes]([times]: [Int], [name]: [String]) {","[var] [result] = [\"\"]","[print]([result])","}"],
    notes:{2:"print matches Void."}}),
  L({id:"f6", day:"05", ch:"Functions", title:"Parameter labels", hint:"External vs internal.",
    lines:["[func] [setAge]([for] [person]: [String], [to] [value]: [Int]) {","[print]([person])","}"],
    notes:{0:"Call site: setAge(for:to:)."}}),
  L({id:"f7", day:"05", ch:"Functions", title:"Omitting labels", hint:"_ hides the external name.",
    lines:["[func] [greet]([_] [name]: [String]) {","[print]([name])","}"],
    notes:{0:"Call as greet(Ada)."}}),
  L({id:"f8", day:"05", ch:"Functions", title:"Default parameters", hint:"Caller can skip.",
    lines:["[func] [greet]([name]: [String] = [\"World\"]) {","[print]([name])","}"],
    notes:{0:"greet() uses World."}}),
  L({id:"f9", day:"05", ch:"Functions", title:"Variadic", hint:"... means any number.",
    lines:["[func] [sum]([numbers]: [Int]...) [->] [Int] {","[return] [numbers].[reduce](0, +)","}"],
    notes:{0:"numbers is [Int]."}}),
  L({id:"f10", day:"05", ch:"Functions", title:"inout", hint:"Function may assign back.",
    lines:["[func] [doubleInPlace]([_] [number]: [inout] [Int]) {","[number] [*=] [2]","}"],
    notes:{0:"Caller writes doubleInPlace(&x)."}})
];
